/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin_page`; params?: Router.UnknownInputParams; } | { pathname: `/document`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/listing_summaries`; params?: Router.UnknownInputParams; } | { pathname: `/main`; params?: Router.UnknownInputParams; } | { pathname: `/navigation_bar`; params?: Router.UnknownInputParams; } | { pathname: `/project`; params?: Router.UnknownInputParams; } | { pathname: `/property`; params?: Router.UnknownInputParams; } | { pathname: `/property_summary`; params?: Router.UnknownInputParams; } | { pathname: `/settings_page`; params?: Router.UnknownInputParams; } | { pathname: `/sign_in`; params?: Router.UnknownInputParams; } | { pathname: `/sign_up`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/admin_page`; params?: Router.UnknownOutputParams; } | { pathname: `/document`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/listing_summaries`; params?: Router.UnknownOutputParams; } | { pathname: `/main`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation_bar`; params?: Router.UnknownOutputParams; } | { pathname: `/project`; params?: Router.UnknownOutputParams; } | { pathname: `/property`; params?: Router.UnknownOutputParams; } | { pathname: `/property_summary`; params?: Router.UnknownOutputParams; } | { pathname: `/settings_page`; params?: Router.UnknownOutputParams; } | { pathname: `/sign_in`; params?: Router.UnknownOutputParams; } | { pathname: `/sign_up`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/admin_page${`?${string}` | `#${string}` | ''}` | `/document${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/listing_summaries${`?${string}` | `#${string}` | ''}` | `/main${`?${string}` | `#${string}` | ''}` | `/navigation_bar${`?${string}` | `#${string}` | ''}` | `/project${`?${string}` | `#${string}` | ''}` | `/property${`?${string}` | `#${string}` | ''}` | `/property_summary${`?${string}` | `#${string}` | ''}` | `/settings_page${`?${string}` | `#${string}` | ''}` | `/sign_in${`?${string}` | `#${string}` | ''}` | `/sign_up${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin_page`; params?: Router.UnknownInputParams; } | { pathname: `/document`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/listing_summaries`; params?: Router.UnknownInputParams; } | { pathname: `/main`; params?: Router.UnknownInputParams; } | { pathname: `/navigation_bar`; params?: Router.UnknownInputParams; } | { pathname: `/project`; params?: Router.UnknownInputParams; } | { pathname: `/property`; params?: Router.UnknownInputParams; } | { pathname: `/property_summary`; params?: Router.UnknownInputParams; } | { pathname: `/settings_page`; params?: Router.UnknownInputParams; } | { pathname: `/sign_in`; params?: Router.UnknownInputParams; } | { pathname: `/sign_up`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
